plugins:
  phan:
    enabled: true
    config:
      file_extensions: "php"
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - src/test/**
        - app/src/test/**

